services:
  mysql:
    image: 'mysql:8.1.0'
    environment:
      - 'MYSQL_DATABASE=nyrdb'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '33066:3306'
    volumes:
      - ./docker/storage/data:/var/lib/mysql
